version: "3.9"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: clinica
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
    ports: ["3306:3306"]
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 5s
      retries: 10
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: clinica
      DB_USERNAME: admin
      DB_PASSWORD: 123
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
  nginx:
    image: nginx:1.25
    depends_on: [api]
    ports: ["8080:80"]
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api
    ports: ["3000:3000"]
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm","run","dev","--","-p","3000"]
  mailhog:
    image: mailhog/mailhog
    ports: ["8025:8025"]
volumes:
  dbdata:
